# Generated by Django 4.2.7 on 2025-08-05 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='카테고리 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리들',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': '서비스', 'verbose_name_plural': '서비스들'},
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='서비스 이미지'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='추천 서비스'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_advance_booking',
            field=models.PositiveIntegerField(default=30, verbose_name='최대 예약 가능 시간(일)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_advance_booking',
            field=models.PositiveIntegerField(default=0, verbose_name='최소 예약 가능 시간(시간)'),
        ),
        migrations.AddField(
            model_name='service',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='재고 수량'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.category', verbose_name='카테고리'),
        ),
    ]
