# Generated by Django 4.2.7 on 2025-08-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_category_alter_service_options_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제공자명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='제공자 설명')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='providers/', verbose_name='제공자 이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('specialties', models.TextField(blank=True, null=True, verbose_name='전문 분야')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='경력 연차')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '서비스 제공자',
                'verbose_name_plural': '서비스 제공자들',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.serviceprovider', verbose_name='서비스 제공자'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.serviceprovider', verbose_name='서비스 제공자'),
        ),
    ]
