# Generated by Django 4.2.7 on 2025-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_serviceprovider_reservation_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='비밀번호'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='로그인 아이디'),
        ),
    ]
